# Site settings
title: Adnan Khan
email: adnanekhanweb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Developer. Student. Personal Webpage/Resume Site for Adnan Khan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://Adnanekhan.github.io" # the base hostname & protocol for your site
twitter_username: adnanthekhan
github_username:  AdnaneKhan

# Build settings
markdown: kramdown
